GUI.ButtonLock();
GUI.SetDialogVisible(1);
GUI.ShowImage("feiw_ys.png",left,300);
GUI.ShowRoleName("菲");
GUI.ShowText("敌方的溃军就在西南方的山岳中盘踞，为了月曜镇的安全，请尽快铲除他们。",1);
GUI.ClearText();
GUI.ShowText("作战开始！",1);
GUI.ClearText
GUI.ShowRoleName("");
GUI.ShowImage("",right,300);
GUI.ShowImage("",left,300);
GUI.SetDialogVisible(0);
GUI.StoryOver();