GUI.ButtonLock();
GUI.SetDialogVisible(1);
GUI.ShowImage("feiw_cj.png",left,300);
GUI.ShowRoleName("∑∆");
GUI.ShowText("≥«±§«¯”Ú ß ÿ£°≥∑ÕÀ∞…£°",1);
GUI.ClearText();
GUI.ShowRoleName("");
GUI.ShowImage("",right,300);
GUI.ShowImage("",left,300);
GUI.SetDialogVisible(0);
GUI.StoryOver();