GUI.ButtonLock();
GUI.SetDialogVisible(1);
GUI.ShowImage("feiw_cj.png",left,300);
GUI.ShowRoleName("菲");
GUI.ShowText("诺斯军以强悍闻名大陆，不要与他们的巨剑步兵硬拼！",1);
GUI.ClearText();
GUI.ShowText("与温菲尔德军保持一致，坚守住城堡！它一旦失守月曜镇就危险了！",1);
GUI.ClearText
GUI.ShowRoleName("");
GUI.ShowImage("",right,300);
GUI.ShowImage("",left,300);
GUI.SetDialogVisible(0);
GUI.StoryOver();