GUI.ButtonLock();
GUI.SetDialogVisible(1);
GUI.ShowImage("kasite_cj.png",left,300);
GUI.ShowRoleName("卡斯特");
GUI.ShowText("前方就是地势平缓的地带了，诺斯军不可能追得上我们了！",1);
GUI.ClearText();
GUI.ShowImage("aoliwa_ys.png",right,300);
GUI.ShowRoleName("奥莉瓦");
GUI.ShowText("但是齐塔……",1);
GUI.ClearText
GUI.ShowImage("ashaniyaw_sx.png",left,300);
GUI.ShowRoleName("阿莎尼娅");
GUI.ShowText("我们现在能做的，只有为他祈祷了吗……",1);
GUI.ClearText
GUI.ShowRoleName("");
GUI.ShowImage("",right,300);
GUI.ShowImage("",left,300);
GUI.SetDialogVisible(0);
GUI.StoryOver();