GUI.ButtonLock();
GUI.SetDialogVisible(1);
GUI.ShowImage("qitaw_ys.png",left,300);
GUI.ShowRoleName("齐塔");
GUI.ShowText("此战目标是掩护卡斯特一行从东南方撤退，不要直接跟诺斯军硬碰硬，坚守住山道拖延时间即可。",1);
GUI.ClearText();
GUI.ShowText("那么先把敌军尽可能吸引过来吧！",1);
GUI.ClearText
GUI.ShowRoleName("");
GUI.ShowImage("",right,300);
GUI.ShowImage("",left,300);
GUI.SetDialogVisible(0);
GUI.StoryOver();