void main(
	float2 uv: TEXCOORD0, 
	
	out float4 oColour	: COLOR,

	uniform sampler2D lightTex: register(s0)
	)
{
	float4 light = tex2D(lightTex, uv);
	float4 BloomThreshold = float4(0.6, 0.6, 0.6, 1.0);
	
	//light -= 1;
	//float4 bright4= -6 * light * light + 2; 
	//float bright = dot( bright4, float4( 0.333333, 0.333333, 0.333333, 0) );
	//light += bright + 0.6;

	oColour  = saturate((light - BloomThreshold) / (1 - BloomThreshold));//ight;
}
