void main(
	float4	position	:	POSITION,
	float2	uv			:	TEXCOORD0,
	float2	uv1			:	TEXCOORD1,
	float2	uv2			:	TEXCOORD2,
	float2	uv3			:	TEXCOORD3,

	out	float4	oPosition	:	POSITION,
	out	float2	oUv			:	TEXCOORD0,
	out	float2	oUv1		:	TEXCOORD1,
	out	float2	oUv2		:	TEXCOORD2,
	out	float2	oUv3		:	TEXCOORD3,

	uniform	float4x4	worldViewProj
	)
{
	oPosition = mul(worldViewProj, position);
	oUv = uv;
	oUv1 = uv1;
	oUv2 = uv2;
	oUv3 = uv3;
}