void main(
	float4	position	:	POSITION,
	float3	normal		:	NORMAL,
	float2	uv			:	TEXCOORD0,

	out	float4	oPosition	:	POSITION,
	out	float3	oNormal		:	TEXCOORD0,
	out	float	oDepth		:	TEXCOORD1,
	out	float2	oUv			:	TEXCOORD2,

	uniform	float4x4	worldViewProj,
	uniform	float3x4	worldMatrix
	)
{
	oPosition = mul(worldViewProj, position);
	oDepth.x = oPosition.z;
	oNormal = mul((float3x3)worldMatrix, normal);
	oUv = uv;
}